import type { Metadata } from "next";
import DateOfToday from "./component.tsx/DateOfToday";
import "./globals.css";

export const metadata: Metadata = {
	title: "My Hero App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const todayDate = new Date().toLocaleDateString();
	return (
		<html lang="ja">
			<body className="flex flex-col min-h-screen">
				<header className="bg-blue-500 text-white p-4">
					<h1 className="text-2xl font-bold mb-4">My Hero App</h1>
					<nav className="flex items-center justify-between">
						<div className="flex space-x-2">
							<a
								href="/"
								className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition"
							>
								トップ
							</a>
							<a
								href="/myHeroes"
								className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition"
							>
								一覧
							</a>
						</div>
						<DateOfToday date={todayDate} />
					</nav>
				</header>
				<main className="flex-1 p-4">{children}</main>
				<footer className="bg-gray-800 text-white text-center p-4">
					© 2024 My Hero App
				</footer>
			</body>
		</html>
	);
}
