import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "My Hero App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className="flex flex-col min-h-screen">
				<header className="bg-blue-500 text-white p-4">
					<h1 className="text-lg font-bold">My Hero App</h1>
					<nav>
						<a href="/" className="mr-4 hover:underline">
							トップ
						</a>
						<a href="/myHeroes" className="hover:underline">
							一覧
						</a>
					</nav>
				</header>
				<main className="flex-1 p-4">{children}</main>
				<footer className="bg-gray-800 text-white text-center p-4">
					© 2024 My Hero App
				</footer>
			</body>
		</html>
	);
}
